import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({
  subsets: ["latin"],
  weight: ["500", "600"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const savedMode = localStorage.getItem("app-mode") || "dark";
                  const savedTheme = localStorage.getItem("app-theme") || "rose";
                  const root = document.documentElement;
                  root.classList.remove("dark");
                  if (savedMode === "dark" || (savedMode === "system" && window.matchMedia("(prefers-color-scheme: dark)").matches)) {
                    root.classList.add("dark");
                  }
                  root.classList.add("theme-" + savedTheme);
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body className={`${inter.className} antialiased text-[14px]`} suppressHydrationWarning={true}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
