import { initializeApp, getApps, getApp } from "firebase/app";
import { getMessaging, getToken, onMessage } from "firebase/messaging";

const firebaseConfig = {
  apiKey: "AIzaSyC9IGreaTSma8EKzr80HBoTT1UI1UfTMWE",
  authDomain: "spike-24eed.firebaseapp.com",
  projectId: "spike-24eed",
  storageBucket: "spike-24eed.firebasestorage.app",
  messagingSenderId: "659081292797",
  appId: "1:659081292797:web:4378a440ca96ea8146c794",
  measurementId: "G-J9BTWRQ43Y"
};

// Initialize Firebase App
const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();

let messaging = null;

if (typeof window !== "undefined" && "serviceWorker" in navigator) {
  try {
    messaging = getMessaging(app);
  } catch (error) {
    console.log("⚠️ Firebase Messaging is not supported on this browser/environment:", error);
  }
}

export { app, messaging };

// Request notifications permissions and retrieve FCM push token
export const initPushNotifications = async () => {
  if (typeof window === "undefined" || !messaging) return null;

  try {
    // 1. Request permission
    const permission = await Notification.requestPermission();
    if (permission === "granted") {
      console.log("🔔 Notification permission granted!");
      
      // 2. Register Service Worker and retrieve token
      try {
        const token = await getToken(messaging, {
          // If a custom VAPID key is generated by the user, they can supply it.
          // Fallback to auto-token retrieval
        });
        
        if (token) {
          console.log("🔥 Firebase FCM Token:", token);
          // Sync token to backend
          await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/v1/users/me/fcm-token`, {
            method: "PUT",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({ fcmToken: token }),
            credentials: "include",
          });
        }
        return token;
      } catch (tokenError) {
        console.warn("⚠️ Could not fetch FCM token (likely requires a valid VAPID Key set in firebase.js):", tokenError);
      }
    }
  } catch (error) {
    console.error("❌ Error requesting push notification permission:", error);
  }
  return null;
};
